// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace MinaGlosor.Web.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class PostPracticeSession : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostPracticeSession));
        
        string IMigrationMetadata.Id
        {
            get { return "201404171952424_PostPracticeSession"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
