// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace MinaGlosor.Web.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class User_CreatedDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_CreatedDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201403102000267_User_CreatedDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
